//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalromExam.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightData
    {
        public int FlightDataId { get; set; }
        public string Destination { get; set; }
        public string FlightStatus { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<int> FlownMiles { get; set; }
    }
}
